world_bounds:
    min: [0.0, 0.0, 0.0]
    max: [8.0, 4.0, 3.0] # Yükseklik 3 metreye çıkarıldı

obstacles:
  # Tam boy kolonlar (Z: 0.0'dan 3.0'a)
  - min: [1.8, 1.0, 0.0] 
    max: [2.2, 1.4, 3.0]
  - min: [5.8, 2.5, 0.0]
    max: [6.2, 2.9, 3.0]
  
  # Alçak engeller (Masa/Ekipman - Z: 0.0'dan 1.2'ye)
  - min: [3.5, 1.5, 0.0]
    max: [4.5, 2.5, 1.2]
  - min: [0.5, 2.5, 0.0]
    max: [1.2, 3.5, 0.9]
  - min: [6.5, 0.5, 0.0]
    max: [7.5, 1.5, 1.1]

  # Yüksek asılı engeller (Aydınlatma/Havalandırma - Z: 2.2'den 3.0'a)
  - min: [3.0, 0.0, 2.2]
    max: [5.0, 0.8, 3.0]
  - min: [3.0, 3.2, 2.2]
    max: [5.0, 4.0, 3.0]
    
  # Küçük serpiştirilmiş kutular (Z: 0.0'dan 0.6'ya)
  - min: [2.5, 3.0, 0.0]
    max: [2.9, 3.4, 0.6]
  - min: [5.0, 0.8, 0.0]
    max: [5.4, 1.2, 0.6]

agents:
  - id: 0 # Köşeden köşeye (Alçak seviye uçuş)
    start: [0.4, 0.4, 0.5]
    goal:  [7.6, 3.6, 0.5]

  - id: 1 # Köşeden köşeye (Yüksek seviye uçuş)
    start: [7.6, 0.4, 2.5]
    goal:  [0.4, 3.6, 2.5]

  - id: 2 # Orta hat geçişi (Zikzak yapmak zorunda)
    start: [0.4, 2.0, 1.5]
    goal:  [7.6, 2.0, 1.5]

  - id: 3 # Ters orta hat
    start: [7.6, 2.5, 1.8]
    goal:  [0.4, 1.5, 1.8]

  - id: 4 # Dikey kesen hat (Y ekseni boyunca)
    start: [4.0, 0.4, 2.0]
    goal:  [4.0, 3.6, 2.0]

  - id: 5 # Kısa mesafe çapraz (Engel yoğun bölge)
    start: [2.0, 3.6, 1.0]
    goal:  [6.0, 0.4, 1.0]
